---
discovery:
  # platform_api_prefix is not required to change for ApiConnect on Cloud
  datasource_type: nginx
  # supported values are istio, nginx
  datasource_name: myistio-data-source
  platform_api_prefix: platform-api
  apic_host_domain: us-east-a.apiconnect.automation.ibm.com
  provider_org: myOrgName
  api_key: xxxxxx
  namespace: istio-system
  telemetry_namespace: istio-system
logging:
  log_level: info
  # supported values are json and console
  log_encoder: json

images:
  api_discovery_collector: ghcr.io/ibm-apiconnect/api-discovery-otel-collector:20240522-104525
