---
discovery:
  # platform_api_prefix is not required to change for ApiConnect on Cloud
  # supported values are istio, nginx
  datasource_type: nginx
  datasource_name: myistio-data-source
  platform_api_prefix: platform-api
  apic_host_domain: us-east-a.apiconnect.automation.ibm.com
  provider_org: myOrgName
  api_key: xxxxxx
  namespace: istio-system
  # supported values are telemetry, envoyfilter
  collector_mode: telemetry
  telemetry_namespace: istio-system
  # Enable the processor and edit the processor-configmap to choose values for batch and memory_limiter
  # supported values are enabled and disabled
  processors: disabled
logging:
  log_level: info
  # supported values are json and console
  log_encoder: json
  # supported values are basic and detailed
  debugexporter_verbosity: basic

images:
  api_discovery_collector: ghcr.io/ibm-apiconnect/api-discovery-otel-collector:56-2025-01-15-07-30-30.amd64
