apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-configmap
  namespace: {{ .Values.discovery.namespace }}
data:
  processor-cm.yaml: |
{{- if (eq .Values.discovery.processors "enabled") }}
    processors:
      batch:
        send_batch_size: 10000
        send_batch_max_size: 11000
        timeout: "30s"
      memory_limiter:
        check_interval: "1s"
        limit_mib: 256
        spike_limit_mib: 51
    service:
      pipelines:
        traces:
          processors: [attributes/ibm-apiconnect,redaction/ibm-apiconnect,filter/ibm-apiconnect,transform/ibm-apiconnect,resource/ibm-apiconnect,batch,memory_limiter]
#{{- else if or (eq .Values.discovery.processors "disabled") (not (.Values.discovery.processors)) }}
{{- else }}
    processors: {}
{{- end }}