---
{{- if (eq .Values.discovery.datasource_type "istio") }}
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: api-discovery-otel
  namespace: {{ .Values.discovery.telemetry_namespace }}
spec:
#  accessLogging:
#    - providers:
#      - name: discoveryOtelCollector
  tracing:
  - providers:
    - name: discoveryOtelCollector
    randomSamplingPercentage: 100
    {{- if .Values.discovery.datasource_name }}
    customTags:
      "ibm-api-discovery-datasource.name":
        literal:
          value: {{ .Values.discovery.datasource_name }}
    {{- end }}
{{- end }}