---
{{- if and (eq .Values.discovery.datasource_type "istio" ) (eq .Values.discovery.collector_mode "telemetry") }}
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: api-discovery-otel
  namespace: {{ .Values.discovery.telemetry_namespace }}
spec:
#  accessLogging:
#    - providers:
#      - name: discoveryOtelCollector
  tracing:
  - providers:
    - name: discoveryOtelCollector
    randomSamplingPercentage: 100
{{- end }}
